=== iamthechad/frame2/Frame2/framework/src/frame2-template_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
The DTD for the Frame2 Template Configuration, Version 1.0.

  <!DOCTYPE template-config PUBLIC
  "-//Megatome Technologies//DTD Frame2 Template Plugin 1.0//EN"
  "http://frame2.sourceforge.net/dtds/frame2-template_1_0.dtd">
-->

<!--
The template-config element is the root element of a Frame2
template configuration file.
-->

<!ELEMENT template-config  (templates)>

<!--
The templates element is the root element for all defined templates
in the configuration file.
-->

<!ELEMENT templates (template*)>

<!--
Individual template declarations.
-->

<!ELEMENT  template (put*)>
<!ATTLIST template name CDATA #REQUIRED
                    path CDATA #REQUIRED
>
                    
<!--
Put elements represent placeholders for template content.

Example:
<template name="sample" path="some.jsp">
   <put name="header" path="header.jsp"/>
   <put name="footer" path="footer.jsp"/>
</template>
-->

<!ELEMENT  put EMPTY>
<!ATTLIST put name CDATA #REQUIRED
               path CDATA #REQUIRED>

=== iamthechad/frame2/Frame2/test_app/WEB-INF/templates/templates.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE template-config PUBLIC
  "-//Megatome Technologies//DTD Frame2 Template Plugin 1.0//EN"
  "http://frame2.sourceforge.net/dtds/frame2-template_1_0.dtd">
 
<template-config>
	<templates>
		<template name="template1" path="xxx.jsp">
			<put name="header" path="yyy.jsp"/>
			<put name="nav" path="yyy.jsp"/>
			<put name="footer" path="yyy.jsp"/>
		</template>
      <template name="template2" path="template2.jsp">
         <put name="header" path="header2.jsp"/>
         <put name="nav" path="nav2.jsp"/>
         <put name="footer" path="footer2.jsp"/>
      </template>
      <template name="template3" path="template3.jsp">
         <put name="header" path="header2.jsp"/>
         <put name="nav" path="nav2.jsp"/>
         <put name="footer" path="footer2.jsp"/>
      </template>
      <template name="template_headeronly" path="template_headeronly.jsp">
         <put name="header" path="header2.jsp"/>
      </template>
      <template name="template_paramsonly" path="template_paramsonly.jsp">
         <put name="header" path="header2.jsp"/>
      </template>
      <template name="template_negativeget_name" path="template_negativeget_name.jsp">
         <put name="header" path="header2.jsp"/>
      </template>
   </templates>
</template-config>

=== iamthechad/frame2/Frame2/framework/test/src/org/megatome/frame2/template/config/multTag-Put-Template.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE template-config PUBLIC
  "-//Megatome Technologies//DTD Frame2 Template Plugin 1.0//EN"
  "http://frame2.sourceforge.net/dtds/frame2-template_1_0.dtd">

<template-config>
<templates>
	<template name="xxx1" path="xxx.jsp">
		<put name="yyy1" path="yyy.jsp"/>
		<put name="yyy2" path="yyy.jsp"/>
	</template>
	<template name="xxx2" path="xxx.jsp"/>		
	<template name="xxx3" path="xxx.jsp">		
		<put name="yyy1" path="yyy.jsp"/>
	</template>
</templates>
</template-config>
