=== iamthechad/frame2/Frame2/framework/src/frame2-config_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
The DTD for the Frame2 Configuration File, Version 1.0

  <!DOCTYPE frame2-config PUBLIC
  "-//Megatome Technologies//DTD Frame2 Configuration 1.0//EN"
  "http://frame2.sourceforge.net/dtds/frame2-config_1_0.dtd">
-->
<!--
The frame2-config element is the root element of a Frame2
configuration file.
-->
<!ELEMENT frame2-config (global-forwards?, events?, event-mappings?, event-handlers?, exceptions?, plugins?, request-processors?)>
<!--
The global forward elements specify named targets for how
responses should be created. Forwards are used in both the
global-forwards and in the event handlers.
-->
<!ELEMENT global-forwards (forward*)>
<!--
Forwards are named entities that describe how a response will be
generated.  There are four types of declarable forwards:

  - HTMLResource: Forward to an HTTP that will generate a view
  for an HTML client.  In this case the path represents the path
  to the resource.

  - XMLResource: Generate a response by marshalling the value
  stored within the request attributes at the key value specified
  in the path.

  - XMLResponder: Generate a response by making a call on a
  user-defined Responder object. The type of Responder is
  specified by the path.

  - Event: Continue execution on the request by passing control
  to a new event.  The event name is specified by the path.
-->
<!ELEMENT forward EMPTY>
<!ATTLIST forward
	name CDATA #REQUIRED
	type (HTMLResource | XMLResource | XMLResponder | event) #REQUIRED
	path CDATA #REQUIRED
>
<!--
Events bind requests and their data to event types.  When the
framework receives requests it instantiates the appropriate event
type, populating it, and then passing control through the
corresponding event mapping.  The optional resolve-as parameter
applies to processing XML requests.  The values have the
following effect:

  - passthru: The XML request is wrapped in an XMLEventWrapper
  and processed with the corresponding event-mapping.

  - children: The child elements of the XML request will each be
  processed with the event-mapping for the parent node.

  - parent: The parent element of the XML request will be
  processed with the event-mapping of the parent node (this is
  the default).
-->
<!ELEMENT events (event*)>
<!ELEMENT event EMPTY>
<!ATTLIST event
	name CDATA #REQUIRED
	resolveAs (passthru | children | parent) #IMPLIED
	type CDATA #IMPLIED
>
<!--
Event mapping elements define how events are to be processed.
The inputView resolves to a forward if validation of the event
fails.  The cancelView similarly resolves to a forward if the
submit was actually a cancel. Validate indicates whether
automatic validation on the event should be executed.  The
handlers will be called in order of declaration. Up to two
default views may be specified, one each for HTML and XML (see
the view element).  Security specifies roles that the user must
be in (via the J2EE container security) in order to process the
event.
-->
<!ELEMENT event-mappings (event-mapping*)>
<!ELEMENT event-mapping (handler*, view*, security?)>
<!ATTLIST event-mapping
	eventName CDATA #REQUIRED
	inputView CDATA #IMPLIED
	cancelView CDATA #IMPLIED
	validate (true | false) #IMPLIED
>
<!ELEMENT handler EMPTY>
<!ATTLIST handler
	name CDATA #REQUIRED
>
<!ELEMENT security (role+)>
<!ELEMENT role EMPTY>
<!ATTLIST role
	name CDATA #REQUIRED
>
<!--
Views act as default specifications for how the response should
be generated if none of the event handlers specifies a view.  The
type attribute indicates whether the view applies to HTML
responses, XML responses, or both.
-->
<!ELEMENT view EMPTY>
<!ATTLIST view
	type (HTML | XML | Both) #REQUIRED
	forwardName CDATA #REQUIRED
>
<!--
Event handlers elements define the mapping between an event
handler name and a user-implementation of the EventHandler
interface.  Input params to the handler and local forward (that
apply whenever the handler is invoked) may optionally be declared
as well.
-->
<!ELEMENT event-handlers (event-handler*)>
<!ELEMENT event-handler ((init-param | forward)*)>
<!ATTLIST event-handler
	name CDATA #REQUIRED
	type CDATA #REQUIRED
>
<!--
Initialization parameters may be specified for each handler.  The
parameters are provided to the handler on each call through the
Context.
-->
<!ELEMENT init-param EMPTY>
<!ATTLIST init-param
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!--
Exception elements specify a mapping between an Throwable type
and a view.  If an exception is encountered when processing an
event execution will proceed to the forward specified in the
view.  Up to two views may be specified, one each of the XML and
HTML type.
-->
<!ELEMENT exceptions (exception*)>
<!ELEMENT exception (view+)>
<!ATTLIST exception
	requestKey CDATA #REQUIRED
	type CDATA #REQUIRED
>
<!--
Plugin elements specify classes that take advantage of the
Frame2 plugin framework. Input parameters to the plugin class
may be optionally declared.
-->
<!ELEMENT plugins (plugin*)>
<!ELEMENT plugin (init-param*)>
<!ATTLIST plugin
	name CDATA #REQUIRED
	type CDATA #REQUIRED
>
<!--
Request Processor elements specify classes that extend either
HTTPRequestProcessor, SoapRequestProcessor, or
an implemention of RequestProcessorBase. 
-->
<!ELEMENT request-processors ((http-request-processor?,soap-request-processor?))>
<!ELEMENT http-request-processor EMPTY>
<!ATTLIST http-request-processor
	type CDATA #REQUIRED>
<!ELEMENT soap-request-processor EMPTY>
<!ATTLIST soap-request-processor
	type CDATA #REQUIRED>

=== iamthechad/frame2/Frame2/framework/test/src/org/megatome/frame2/front/soapRequestNegativeClassReqProc.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE frame2-config PUBLIC
  "-//Megatome Technologies//DTD Frame2 Configuration 1.0//EN"
  "http://frame2.sourceforge.net/dtds/frame2-config_1_0.dtd">

<frame2-config>
   <global-forwards>
   </global-forwards>
   <events>
   </events>
   <event-mappings>
   </event-mappings>
   <event-handlers>
   </event-handlers>
   <plugins>
   </plugins>
   <request-processors>
     <soap-request-processor type="org.megatome.frame2.front.RequestProcessorNoImple"/>
   </request-processors>
</frame2-config>

=== iamthechad/frame2/Frame2/framework/test/src/org/megatome/frame2/front/config/events-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE frame2-config PUBLIC
  "-//Megatome Technologies//DTD Frame2 Configuration 1.0//EN"
  "http://frame2.sourceforge.net/dtds/frame2-config_1_0.dtd">

<frame2-config>
   <global-forwards>
      <forward name="xx1" type="HTMLResource" path="xxxpath1" />
      <forward name="xx2" type="HTMLResource" path="xxxpath2" />
      <forward name="xx3" type="HTMLResource" path="xxxpath3" />
   </global-forwards>
   <events>
      <event name="event1" type="com.frame2.event1"/>
      <event name="event2" type="com.frame2.event2"/>
      <event name="event3" type="com.frame2.event3"/>
   </events>
</frame2-config>

=== iamthechad/frame2/Frame2/framework/test/src/org/megatome/frame2/front/test-wsconfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE frame2-config PUBLIC
  "-//Megatome Technologies//DTD Frame2 Configuration 1.0//EN"
  "http://frame2.sourceforge.net/dtds/frame2-config_1_0.dtd">

<frame2-config>
  <global-forwards>
    <forward name="orderResult" type="XMLResource" path="key1"/>
    <forward name="ack" type="XMLResponder" path="org.megatome.frame2.front.AckResponder"/>
    <forward name="ev13forward" type="event" path="event2"/>
    <forward name="view4" type="HTMLResource" path="/view4.jsp"/>
    <forward name="view4" type="XMLResource" path="testXmlResource"/>
    <forward name="pass" type="XMLResource" path="passthruResponse"/>
  </global-forwards>
  <events>
    <event name="purchaseOrder" resolveAs="parent"
           type="org.megatome.frame2.jaxbgen.impl.PurchaseOrderImpl"/>
    <event name="POResponderOrder" resolveAs="parent"
           type="org.megatome.frame2.jaxbgen.impl.PurchaseOrderImpl"/>
    <event name="POTestChildren" resolveAs="children"
           type="org.megatome.frame2.jaxbgen.impl.PurchaseOrderImpl"/>
    <event name="comment" resolveAs="parent"
           type="org.megatome.frame2.jaxbgen.impl.CommentImpl"/>
    <event name="event2"
           type="org.megatome.frame2.front.Event2"/>
    <event name="POTestChildrenMixedData" resolveAs="children"
           type="org.megatome.frame2.jaxbgen.impl.PurchaseOrderImpl"/>
    <event name="passthruEvent" resolveAs="passthru"
           type="org.megatome.frame2.event.xml.SimplePassthruEvent"/>
  </events>
  <event-mappings>
    <event-mapping eventName="purchaseOrder"
                   validate="true">
      <handler name="purchaseOrderHandler"/>
      <security>
        <role name="admin"/>
        <role name="guest"/>
      </security>
    </event-mapping>
    <event-mapping eventName="POResponderOrder"
                   validate="true">
      <handler name="POResponderHandler"/>
      <view type="XML" forwardName="ack"/>
    </event-mapping>
    <event-mapping eventName="POTestChildrenMixedData"
                   validate="true">
      <handler name="POResponderHandler"/>
      <view type="XML" forwardName="ack"/>
    </event-mapping>
    <event-mapping eventName="POTestChildren"
                   validate="true">
      <handler name="POResponderHandler"/>
      <view type="XML" forwardName="ack"/>
    </event-mapping>
    <event-mapping eventName="comment"
                   validate="false">
      <handler name="handlerThrowingException"/>
      <view type="XML" forwardName="ack"/>
    </event-mapping>
    <event-mapping eventName="event2"
                   inputView="view1" validate="true">
      <handler name="ev1handler1"/>
      <handler name="ev2handler1"/>
      <view type="Both" forwardName="view4"/>
      <security>
        <role name="admin"/>
        <role name="sales"/>
        <role name="manager"/>
      </security>
    </event-mapping>
    <event-mapping eventName="passthruEvent"
                   inputView="view1" validate="true">
      <handler name="passthruEventHandler"/>
      <view type="XML" forwardName="pass"/>
    </event-mapping>
  </event-mappings>
  <event-handlers>
    <event-handler name="purchaseOrderHandler"
                   type="org.megatome.frame2.front.PurchaseOrderHandler"/>
    <event-handler name="POResponderHandler"
                   type="org.megatome.frame2.front.POResponderHandler"/>
    <event-handler name="handlerThrowingException"
                   type="org.megatome.frame2.front.HandlerThrowingException">
      <forward name="local14" type="XMLResource" path="testclass1"/>
      <forward name="local14" type="HTMLResource" path="test.jsp"/>
      <forward name="listResponder" type="XMLResponder" path="testLocalListResponder"/>
    </event-handler>
    <event-handler name="ev1handler1"
                   type="org.megatome.frame2.front.Ev1handler1">
      <init-param name="parm1" value="val111"/>
      <init-param name="parm2" value="val112"/>
      <forward name="ev1forward1" type="HTMLResource" path="/ev1.jsp"/>
    </event-handler>
    <event-handler name="ev2handler1"
                   type="org.megatome.frame2.front.Ev2handler1">
      <forward name="ev2forward1" type="HTMLResource" path="/ev2.jsp"/>
      <init-param name="parm1" value="val211"/>
      <init-param name="parm2" value="val212"/>
    </event-handler>
    <event-handler name="passthruEventHandler"
                   type="org.megatome.frame2.front.PassthruTestEventHandler"/>
  </event-handlers>
  <exceptions>
    <exception requestKey="exception"
               type="org.megatome.frame2.front.HandlerExceptionTest">
      <view type="Both" forwardName="ev13forward"/>
    </exception>
  </exceptions>
</frame2-config>

=== iamthechad/frame2/Frame2/framework/test/src/org/megatome/frame2/front/httpRequestProc.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE frame2-config PUBLIC
  "-//Megatome Technologies//DTD Frame2 Configuration 1.0//EN"
  "http://frame2.sourceforge.net/dtds/frame2-config_1_0.dtd">

<frame2-config>
   <global-forwards>
    <forward name="view1" type="HTMLResource" path="/view1.jsp"/>
      <forward name="view3" type="HTMLResource" path="/view3.jsp"/>
      <forward name="view4" type="HTMLResource" path="/view4.jsp"/>
   </global-forwards>
   <events>
     <event name="event1" type="org.megatome.frame2.front.FailsValidationEvent"/>
   </events>
   <event-mappings>
      <event-mapping 
      	 eventName="event1"
         inputView="view4"
         validate="true">
         <handler name="ev1handler1"/>
         <handler name="ev1handler2"/>
		 <view type="HTML" forwardName="view3"/>
      </event-mapping>
   </event-mappings>
   <event-handlers>
    <event-handler
         name="ev1handler1"
         type="org.megatome.frame2.front.Ev1handler1">
         <init-param name="parm1" value="val111"/>
         <init-param name="parm2" value="val112"/>
         <forward name="ev1forward1" type="HTMLResource" path="/ev1.jsp"/>
      </event-handler>
      <event-handler
         name="ev1handler2"
         type="org.megatome.frame2.front.Ev1handler2">
         <forward name="ev1forward2" type="HTMLResource" path="/ev1.jsp"/>
         <init-param name="parm1" value="val121"/>
         <init-param name="parm2" value="val122"/>
      </event-handler>
   </event-handlers>
   <plugins>
   </plugins>
   <request-processors>
   </request-processors>
</frame2-config>

=== iamthechad/frame2/Frame2/test_app/WEB-INF/frame2-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE frame2-config PUBLIC
  "-//Megatome Technologies//DTD Frame2 Configuration 1.0//EN"
  "http://frame2.sourceforge.net/dtds/frame2-config_1_0.dtd">

<frame2-config>
   <global-forwards>
   	  <forward  name="addUserJSP" type="HTMLResource" path="/WEB-INF/jsp/adduser.jsp"/>
   	  <forward name="displayUsersJSP" type="HTMLResource" path="/WEB-INF/jsp/displayusers.jsp"/>
   	  <forward name="displayUsersEvent" type="event" path="displayUsers"/>
        <forward name="ack" type="XMLResponder" path="org.megatome.app.handlers.AckResponder"/>
        <forward name="testTagsJSP" type="HTMLResource" path="/WEB-INF/jsp/testTags.jsp"/>
        <forward name="displayUsersMixedContentJSP" type="HTMLResource" path="/helptest/displayusersMixedContent.jsp"/>
        <forward name="testTemplate2JSP" type="HTMLResource" path="/WEB-INF/jsp/testTemplate2.jsp"/>
        <forward name="testTemplate3JSP" type="HTMLResource" path="/WEB-INF/jsp/testTemplate3.jsp"/>
        <forward name="testTemplate4JSP" type="HTMLResource" path="/WEB-INF/jsp/testTemplate4.jsp"/>
        <forward name="exceptionJSP" type="HTMLResource" path="/WEB-INF/jsp/exceptions.jsp"/>
        
   </global-forwards>
   <events>
      <event  name="addUser" type="org.megatome.app.jaxbgen.impl.UserImpl"/>
      <event name="saveUser" resolveAs="children" type="org.megatome.app.jaxbgen.impl.UserImpl"/>
      <event name="displayUsers" type="test.org.megatome.app.user.DisplayUsers"/>   
      <event name="displayUsersMixedContent" type="test.org.megatome.app.user.DisplayUsers"/>   
      <event name="testTags" type="test.org.megatome.app.user.TestTagEvent"/>  
      <event name="testTemplate2" />    
      <event name="testTemplate3" /> 
      <event name="testTemplate4" /> 
   </events>

   <event-mappings>
      <event-mapping 
          eventName="testTags" cancelView="displayUsersEvent"
          inputView="displayUsersJSP"
          validate="true">           
       <handler name="testTagsHandler"/>
       <view type="HTML" forwardName="testTagsJSP"/>
      </event-mapping>
      <event-mapping 
      	 eventName="addUser"
         inputView="displayUsersJSP"
         validate="false">
		 <view type="HTML" forwardName="addUserJSP"/>
      </event-mapping>
      <event-mapping 
	      	eventName="saveUser"
	         inputView="addUserJSP"
	         validate="true">
         <handler name="addUserHandler"/>
		   <view type="HTML" forwardName="displayUsersEvent"/>
         <view type="XML" forwardName="ack"/>
      </event-mapping>            
      <event-mapping 
      	 eventName="displayUsers"
         inputView="displayUsersJSP"
         validate="false">
         <handler name="displayUsersHandler"/>
		 <view type="HTML" forwardName="displayUsersJSP"/>
      </event-mapping>
      <event-mapping 
          eventName="displayUsersMixedContent">
         <handler name="displayUsersHandler"/>
       <view type="HTML" forwardName="displayUsersMixedContentJSP"/>
      </event-mapping>
      <event-mapping 
          eventName="user"
          validate="true">
         <handler name="addUserHandler"/>
         <handler name="addUser"/>
         <security>
            <role name="admin"/>
            <role name="guest"/>
         </security>
      </event-mapping>
      <event-mapping 
          eventName="testTemplate2" >
         <view type="HTML" forwardName="testTemplate2JSP"/>
      </event-mapping>
      <event-mapping 
          eventName="testTemplate3" >
         <view type="HTML" forwardName="testTemplate3JSP"/>
      </event-mapping>
      <event-mapping 
          eventName="testTemplate4" >
         <view type="HTML" forwardName="testTemplate4JSP"/>
      </event-mapping>
   </event-mappings>

   <event-handlers>
      <event-handler
         name="displayUsersHandler"
         type="test.org.megatome.app.user.DisplayUsersHandler">
      </event-handler>
      <event-handler
         name="addUserHandler"
         type="test.org.megatome.app.user.AddUserHandler">
      </event-handler>
      <event-handler
         name="addUser"
         type="org.megatome.app.handlers.AddUser">
      </event-handler>
      <event-handler
         name="testTagsHandler"
         type="test.org.megatome.app.user.TestTagsHandler">
      </event-handler>
   </event-handlers>

   <plugins>
   	  <plugin name="Templates" type="org.megatome.frame2.template.TemplatePlugin" />
   </plugins>
</frame2-config>
